// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fortune-ball/Current.tsx": () => import("../components/mockups/fortune-ball/Current.tsx"),
  "./components/mockups/fortune-ball/FortuneSample.tsx": () => import("../components/mockups/fortune-ball/FortuneSample.tsx")
};
